// Code generated by MockGen. DO NOT EDIT.
// Source: repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositories is a mock of Repositories interface.
type MockRepositories struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoriesMockRecorder
}

// MockRepositoriesMockRecorder is the mock recorder for MockRepositories.
type MockRepositoriesMockRecorder struct {
	mock *MockRepositories
}

// NewMockRepositories creates a new mock instance.
func NewMockRepositories(ctrl *gomock.Controller) *MockRepositories {
	mock := &MockRepositories{ctrl: ctrl}
	mock.recorder = &MockRepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositories) EXPECT() *MockRepositoriesMockRecorder {
	return m.recorder
}

// AddCounter mocks base method.
func (m *MockRepositories) AddCounter(nameMetric string, val int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCounter", nameMetric, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCounter indicates an expected call of AddCounter.
func (mr *MockRepositoriesMockRecorder) AddCounter(nameMetric, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCounter", reflect.TypeOf((*MockRepositories)(nil).AddCounter), nameMetric, val)
}

// GetMetricAll mocks base method.
func (m *MockRepositories) GetMetricAll() (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricAll")
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricAll indicates an expected call of GetMetricAll.
func (mr *MockRepositoriesMockRecorder) GetMetricAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricAll", reflect.TypeOf((*MockRepositories)(nil).GetMetricAll))
}

// GetMetricCounter mocks base method.
func (m *MockRepositories) GetMetricCounter(nameM string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricCounter", nameM)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricCounter indicates an expected call of GetMetricCounter.
func (mr *MockRepositoriesMockRecorder) GetMetricCounter(nameM interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricCounter", reflect.TypeOf((*MockRepositories)(nil).GetMetricCounter), nameM)
}

// GetMetricGauge mocks base method.
func (m *MockRepositories) GetMetricGauge(nameM string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricGauge", nameM)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetricGauge indicates an expected call of GetMetricGauge.
func (mr *MockRepositoriesMockRecorder) GetMetricGauge(nameM interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricGauge", reflect.TypeOf((*MockRepositories)(nil).GetMetricGauge), nameM)
}

// UpdateGauge mocks base method.
func (m *MockRepositories) UpdateGauge(nameMetric string, val float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", nameMetric, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockRepositoriesMockRecorder) UpdateGauge(nameMetric, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockRepositories)(nil).UpdateGauge), nameMetric, val)
}
